name: PhoenixBotSMP KeepAlive

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes to ensure the bot restarts if needed

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Must match your bot's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Ensure logs folder exists
        run: mkdir -p logs

      - name: Start bot
        run: |
          echo "Starting PhoenixBotSMP..."
          node bot.js
        env:
          MC_SERVERS: ${{ secrets.MC_SERVERS }}  # Example: play.phoenixsmp.qzz.io:20722
          MC_USERNAME: ${{ secrets.MC_USERNAME }} # Example: PhoenixBotSMP
          MC_AUTH: ${{ secrets.MC_AUTH || 'offline' }}
