name: Keep PhoenixSMP Bot Alive

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: npm start
        env:
          MC_SERVERS: ${{ secrets.MC_SERVERS }}
          MC_USERNAME: ${{ secrets.MC_USERNAME }}
          MC_AUTH: ${{ secrets.MC_AUTH }}
