name: PhoenixSMP KeepAlive Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes

jobs:
  keepalive:
    runs-on: ubuntu-latest
    timeout-minutes: 720 # max 12h per run

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install mineflayer

      - name: Load .env
        run: |
          echo "Loading environment variables..."
          cat .env

      - name: Run Bot
        env:
          MC_SERVERS: ${{ secrets.MC_SERVERS || 'play.phoenixsmp.qzz.io:20722' }}
          MC_USERNAME: ${{ secrets.MC_USERNAME || 'PhoenixSMPBot' }}
          MC_AUTH: ${{ secrets.MC_AUTH || 'offline' }}
          MC_EMAIL: ${{ secrets.MC_EMAIL || '' }}
          MC_PASSWORD: ${{ secrets.MC_PASSWORD || '' }}
        run: |
          echo "🚀 Starting PhoenixSMP KeepAlive Bot..."
          node bot.js
