name: PhoenixSMP Bot 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Setup environment
        run: |
          echo "MC_SERVERS=play.phoenixsmp.qzz.io:20722" >> .env
          echo "MC_USERNAME=PhoenixBotSMP" >> .env
          echo "MC_AUTH=offline" >> .env

      - name: Run bot
        run: node bot.js
