# Features
# - Runs 24/7
# - Auto-restarts if bot crashes
# - Auto-updates from GitHub before each restart
# - Rotates logs (keep last 7 days)
# - Persistent 14-hour cooldown using PAT
# - Scheduled every 6 hours

name: PhoenixSMP Bot 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

concurrency:
  group: phoenixsmp-bot
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository using PAT to allow pushing commits
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Check 14-hour cooldown
      - name: Check 14-hour cooldown
        id: cooldown
        run: |
          LAST_RUN_FILE=".github/phoenixbot_last_run.txt"
          NOW=$(date +%s)

          if [ -f "$LAST_RUN_FILE" ]; then
            LAST_RUN=$(cat "$LAST_RUN_FILE")
            ELAPSED=$((NOW - LAST_RUN))
            if [ "$ELAPSED" -lt 50400 ]; then   # 14 hours = 50400 seconds
              echo "Less than 14 hours since last run. Exiting."
              exit 0
            fi
          fi

          echo "14h passed or first run. Continuing..."
          echo $NOW > "$LAST_RUN_FILE"

          # Commit and push the last run timestamp using PAT
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$LAST_RUN_FILE"
          git commit -m "Update PhoenixBot last run timestamp" || echo "No changes to commit"
          git push origin HEAD:main

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Start bot 24/7 with auto-update and log rotation
      - name: Start Bot 24/7
        run: |
          mkdir -p logs
          echo "Starting PhoenixBotSMP 24/7..."

          # Rotate old logs (keep last 7 days)
          LOG_DIR="logs"
          find $LOG_DIR -maxdepth 1 -type f -name "*.log.*" -mtime +6 -exec rm -f {} \;

          while true; do
            # Rotate current log
            if [ -f "$LOG_DIR/bot.log" ]; then
              TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
              mv "$LOG_DIR/bot.log" "$LOG_DIR/bot.log.$TIMESTAMP"
            fi

            echo "Pulling latest code..."
            git reset --hard
            git pull origin main
            npm install

            echo "Running bot..."
            node bot.js >> "$LOG_DIR/bot.log" 2>&1

            echo "Bot crashed or exited. Restarting in 10s..."
            sleep 10
          done
        env:
          MC_SERVERS: ${{ secrets.MC_SERVERS }}
          MC_USERNAME: ${{ secrets.MC_USERNAME }}
          MC_AUTH: ${{ secrets.MC_AUTH || 'offline' }}
          
